# action.yml
name: awyes
description: Run CI. Yas.
branding:
  icon: thumbs-up
  color: white
inputs:
  verbose:
    description: Enable verbose output
    required: false
    default: false
  path:
    description: Path to your awyes resources
    required: false
    default: .
  action:
    description: Regex matching action(s) to run.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
    - ${{ inputs.action }}
    - ${{ inputs.verbose }}
