# action.yml
name: awyes
description: Deploy infra trivially. Yas.
branding:
  icon: thumbs-up
  color: white
inputs:
  config:
    description: Path to your awyes.yml config file.
    required: false
    default: awyes.yml
  clients:
    description: Path to your awyes.py clients file.
    required: false
    default: awyes.py
  deps:
    description: Path to your awyes.py deps file.
    required: false
    default: awyes.txt
  env:
    description: Env within awyes.yml
    required: false
    default: .env
  workflow:
    description: Workflow to run within awyes.yml
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
    - ${{ inputs.clients }}
    - ${{ inputs.deps }}
    - ${{ inputs.env }}
    - ${{ inputs.workflow }}
