# action.yml
name: awyes
description: Run CI. Yas.
branding:
  icon: thumbs-up
  color: white
inputs:
  config:
    description: Path to your awyes.yml config file.
    required: false
    default: awyes.yml
  clients:
    description: Path to your awyes.py clients file.
    required: false
    default: awyes.py
  deps:
    description: Path to your Pipfile.
    required: false
    default: Pipfile
  env:
    description: Env within awyes.yml
    required: false
    default: .env
  action:
    description: Regex matching action(s) to run.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
    - ${{ inputs.clients }}
    - ${{ inputs.deps }}
    - ${{ inputs.env }}
    - ${{ inputs.action }}
