name: Python Package Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Semver bump type for pypi package"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Tag and Deploy New Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump and release pypi
        uses: bb-labs/pypiinthesky@main
        with:
          package_name: awyes
          bump_type: ${{ inputs.bump }}
          pypi_username: __token__
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
